### ISSUE TITLE
Select2 problem with ACF5 and Taxonomy multi-select field

### ISSUE THREAD

**Issue by moorscode** [Yoast/yoast-acf-analysis#26] opened 2017-08-02 08:41 UTC
Whenever a Taxonomy field is created, with multi-select as appearance, the following error is thrown:

`The select2('data') method was called on an element that is not using Select2.`

This is breaking all functionality, and no more data is parsed by the code.

Specifically for branch: https://github.com/Yoast/yoast-acf-analysis/tree/features/acf-5

/cc @kraftner

**Comment by kraftner** [comment] 2017-08-03 07:55
I haven't looked into this yet, but is this with ACF4 or ACF5 Pro? What about the tests?

**Comment by moorscode** [comment] 2017-08-03 08:58
This was tested with ACF5 (see title).
This was breaking while testing it in the WordPress install myself.
This also showed up in the tests with the taxonomy field configured.

**Comment by kraftner** [comment] 2017-08-11 13:40
After some investigation it seems that this broke with ACF 5.6 and the switch from select2 v3 to v4.

As already said in #38 I think we now have to decide if the either up the ACF PRO requirement to >=5.6 or if we attempt to fix this in a way that is compatible with all versions.

Personally, especially because we're not talking about some very old version but the most recent one, I'D say we need to make this work post and pre 5.6.

**Comment by kraftner** [comment] 2017-08-11 14:30
Okay this turned out to be less difficult as expected. As we already have the ACF version in JS I just call select2 differently depending on the ACF version. I've opened a new PR #45 that should fix this issue.

**Comment by kraftner** [comment] 2017-08-16 07:05
Closed via #45

**Closed by kraftner** 2017-08-16 07:05 UTC
Labels: bug

**Comment by Anderrs** [comment] 2018-01-18 00:42
I can confirme that this is still a bug.
It's not really an option to change to Select2 version 3 since a lot of other things break then.

**Comment by kraftner** [comment] 2018-01-18 14:55
@Anderrs This is fixed via #105 which isn't released on .org yet though.
