### ISSUE TITLE
[Feature Request] Make normal position of custom field be defaulted above Yoast SEO box

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoast-acf-analysis#5] opened 2016-04-15 10:42 UTC
The normal position (beneath content) of the custom field is defaulted beneath the Yoast SEO Box. Thus, if you have many boxes open the custom field gets moved all the way down the screen. Another possible  and perhaps better solution would be to include the custom field in the snippet tool.

![position](https://cloud.githubusercontent.com/assets/8238074/14559133/cbd04140-02d4-11e6-9c7e-e29a139968c6.jpg)

![custom field local seo](https://cloud.githubusercontent.com/assets/8238074/14559125/bb64e996-02d4-11e6-8ff6-5f51769092b6.jpg)

**Comment by kraftner** [comment] 2017-08-10 17:02
First I am not sure if this should be here and not instead be filed at the main plugins repo.

The question is also if this should mean that the Yoast SEO box gets pushed further down or you'd prefer the ACF to be pulled further up.

Actually I think this is something this plugin shouldn't mess with at all. People can still reorder stuff if they want. I'd vote close as wont fix -  works as intended. Any other opinions here?

**Comment by kraftner** [comment] 2017-08-11 09:04
Okay I think I'll close this for now, we can still reopen it when good arguments come up - feel free to comment if you disagree.

**Closed by kraftner** 2017-08-11 09:04 UTC
Labels: support
