### ISSUE TITLE
Yoast_ACF_Analysis_Assets->init() triggering error

### ISSUE THREAD

**Issue by cornelRaiu** [Yoast/yoast-acf-analysis#73] opened 2017-09-09 09:28 UTC
in Yoast_ACF_Analysis_Assets on line 16:
`$this->plugin_data = get_plugin_data( dirname( AC_SEO_ACF_ANALYSIS_PLUGIN_FILE )  );` 
get_plugin_data() is expecting the plugin file and not the plugin folder: 

* @param string $plugin_file Path to the main plugin file.
* @param bool   $markup      Optional. If the returned data should have HTML markup applied.
* @param bool   $translate   Optional. If the returned data should be translated. Default true.

That means, line 16 should be replaced with:
`$this->plugin_data = get_plugin_data(AC_SEO_ACF_ANALYSIS_PLUGIN_FILE  );`

**Comment by cornelRaiu** [comment] 2017-09-09 09:30
I just it being reported here: https://github.com/Yoast/yoast-acf-analysis/pull/58

So, no worries. Just wanted to make sure you are aware of it.

**Comment by kraftner** [comment] 2017-09-11 09:24
Duplicate of #57

**Closed by kraftner** 2017-09-11 09:24 UTC
