### ISSUE TITLE
Inclusion of WYSIWYG fields in the analysis

### ISSUE THREAD

**Issue by tjl666** [Yoast/yoast-acf-analysis#40] opened 2017-08-10 10:46 UTC
Hi there,

What a great plugin, thank you so much!  The only limitation we are really hitting is the fact that it does not work with the WYSIWYG fields as sadly we have quite a lot of those on some of our websites.

With that in mind I just wondered whether you had any timescales of when you might be looking to include this field type within the analysis?

Thanks ever so much,
TJ

**Comment by kraftner** [comment] 2017-08-10 10:56
Duplicate of #2

We are currently in the final stages of Version 2 which will also include WYSIWYG.

**Closed** 2017-08-10 10:56 UTC

**Comment by tjl666** [comment] 2017-08-10 13:41
That's great news, and thank you for getting back so quickly :)
