### ISSUE TITLE
Plugin breaks Media Library

### ISSUE THREAD

**Issue by bullpillaren** [Yoast/yoast-acf-analysis#66] opened 2017-08-25 08:38 UTC
[A support thread on wordpress.org](https://wordpress.org/support/topic/plugin-breaks-media-library-3) mentions that the media library is broken. Probably related to [#61](https://github.com/Yoast/yoast-acf-analysis/issues/61).

**Comment by kraftner** [comment] 2017-09-12 14:07
Closing this as I am pretty sure it is a duplicate of #61.

**Closed by kraftner** 2017-09-12 14:07 UTC
