### ISSUE TITLE
Uncaught TypeError when trying to add new row to Flexible Content

### ISSUE THREAD

**Issue by simplemama** [Yoast/yoast-acf-analysis#85] opened 2017-10-13 16:46 UTC
After adding 1 row to a flexible content area in the page editor, as soon as I try to add another, I get an uncaught typeerror.

![image](https://user-images.githubusercontent.com/1275404/31556786-624b0360-b014-11e7-9690-439cfee2f6f5.png)

**Comment by kraftner** [comment] 2017-10-16 15:33
Thanks for reporting. This is a duplicate of #60 fixed by #63 that should soon be released as `2.0.1`.

**Closed by kraftner** 2017-10-16 15:33 UTC
