### ISSUE TITLE
Yoast SEO no longer performing word count. No SEO or Readability analysis

### ISSUE THREAD

**Issue by Shaner18** [Yoast/yoast-acf-analysis#272] opened 2020-08-25 20:37 UTC
* [ x] I've read and understood the [contribution guidelines](https://github.com/Yoast/yoast-acf-analysis/blob/develop/.github/CONTRIBUTING.md).
* [ x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
After upgrading to Yoast SEO 14.8 & WordPress 5.5, Yoast SEO no longer sees the post content, saying on both SEO & readability analysis that the word content is zero. Even going back to posts that Yoast SEO marked as good (green), when I go into edit mode, it no longer see any words. Consequently no analysis take place on the posts. 

### How can we reproduce this behavior?
1. 
2. 
3. 

### Technical info
* WordPress version: 5.5
* ACF Content Analysis for Yoast SEO version: 2.6
* Yoast SEO version: 14.8.1
* ACF type:Pro
* ACF version: 5.9
* Relevant plugins in case of a bug: Classic editor 1.6?

**Comment by ghindle** [comment] 2020-09-01 12:13
I am getting the same issue when using Classic Editor 1.6. It looks like Yoast SEO is enqueuing a different script for the classic editor. The script name is "edit-post-classic".

I added the following to my functions.php as a workaround for the time being.

```php
add_filter('admin_enqueue_scripts', function() {
    $yoast_acf_analysis_plugin_data = get_plugin_data( AC_SEO_ACF_ANALYSIS_PLUGIN_FILE );
    $config = Yoast_ACF_Analysis_Facade::get_registry()->get( 'config' );

    // Post page enqueue.
    if ( wp_script_is( WPSEO_Admin_Asset_Manager::PREFIX . 'post-edit-classic' ) ) {
        wp_enqueue_script(
            'yoast-acf-analysis-post',
            plugins_url( '/js/yoast-acf-analysis.js', AC_SEO_ACF_ANALYSIS_PLUGIN_FILE ),
            [ 'jquery', WPSEO_Admin_Asset_Manager::PREFIX . 'post-edit-classic', 'underscore' ],
            $yoast_acf_analysis_plugin_data['Version'],
            true
        );

        wp_localize_script( 'yoast-acf-analysis-post', 'YoastACFAnalysisConfig', $config->to_array() );
    }
}, 20, 0);
```

**Comment by DanaIliescu** [comment] 2020-09-22 16:59
I deactivated the Classic Editor plugin, but for me the same problem persists!

**Comment by petervinnicombe** [comment] 2020-09-25 19:53
I can confirm this is still an issue - we are using WP5.5.1, Plugin Version 2.7 - ACF Pro 5.9.1, Yoast 14.9...
Yoast can assess everything OK such as titles / meta etc - but cannot assess anything inside the ACF fields... So word count, internal and external link, key phrase in intro, never change from red...

**Comment by markorapaic** [comment] 2020-09-29 01:36
> I deactivated the Classic Editor plugin, but for me the same problem persists!

Deactivating the Classic Editor plugin fixed the issue for me.

**Comment by Shaner18** [comment] 2020-09-30 17:03
removing the classic editor plugin seems to have worked for me as well

**Comment by marthmf** [comment] 2022-12-29 19:37
Experiencing the same issue. Deactivating the Classic Editor plugin worked for me as well. My build is running 

Wordpress 6.1.1
ACF Content Analysis for Yoast SEO 3.0.1
Advanced Custom Fields PRO 6.0.6
Yoast SEO 19.13

Which means everything is up to date as of this comment

**Comment by stephanedemotte** [comment] 2023-01-25 17:03
same issue here

**Comment by jeroenrotty** [comment] 2023-06-01 09:05
Duplicate of #271

**Closed by jeroenrotty** 2023-06-01 09:05 UTC
