### ISSUE TITLE
Social tabs in the meta box on Yoast SEO Premium Fail to display

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/yoast-acf-analysis#21] opened 2017-06-12 19:24 UTC
### What did you expect to happen?
The social previews would display
### What happened instead?
They didnt
### How can we reproduce this behavior?
**1.Activate ACF Analysis**
**2.Visit a post/page**
**3.See social preview section not display**

![screen shot 2017-06-12 at 3 20 12 pm](https://user-images.githubusercontent.com/8238074/27051156-18358846-4f83-11e7-86e0-88fe3178c167.png)

### Technical info
* WordPress version: 4.8
* Yoast SEO Premium: 4.9 
* ACF: 4.4.11
* Yoast ACF Analysis: 1.2.0

**Comment by Pcosta88** [comment] 2017-06-12 19:24
related: https://github.com/Yoast/yoast-acf-analysis/issues/15

**Comment by JoranSchipper** [comment] 2017-07-06 14:36
I'm experiencing the same issue. Any update on this one?

**Comment by Pcosta88** [comment] 2017-07-06 17:32
Hi,

At this moment we have no new updates for this issue. As the Yoast ACF Analysis is a free plugin we would welcome any pull requests to help develop and improve upon it!

**Comment by kraftner** [comment] 2017-08-22 16:40
@Pcosta88 Can you check if this is fixed by 2.0? It seems to be working for me.

**Comment by Pcosta88** [comment] 2017-08-22 17:12
I am not getting it to display.

![screen shot 2017-08-22 at 1 11 05 pm](https://user-images.githubusercontent.com/8238074/29577957-7619c8c4-873b-11e7-9609-72854a3da40d.png)

![screen shot 2017-08-22 at 1 11 31 pm](https://user-images.githubusercontent.com/8238074/29577960-78473a28-873b-11e7-886f-a85c89fd6936.png)

**Comment by Pcosta88** [comment] 2017-08-22 19:21
Please inform the customer of conversation # 216982 when this conversation has been closed.

**Comment by Pcosta88** [comment] 2017-08-24 19:30
Please inform the customer of conversation # 217458 when this conversation has been closed.

**Comment by martijnvaneeghem** [comment] 2017-08-25 10:05
The social previews do not display when editing a post, while they should.

The issue does not give a JS error.

In the local development site, these are the installed plugins and versions when the issue occurs:
ACF Content Analysis for Yoast SEO 2.0.0
Yoast SEO Premium 5.3.2
Advanced Custom Fields 4.4.11

- The issue does not occur when only ACF 4.4.11 is deactivated.
- The issue does not occur when only ACF CA for Yoast SEO 2.0.0 is deactivated
- The issue does not occur when only Yoast SEO 5.3.2 (free) is activated instead of Yoast SEO Premium 5.3.2.
- The issue does not occur when only ACF CA for Yoast SEO 1.2.6 is activated instead of 2.0.0

- The issue occurs also with Yoast SEO Premium 5.2, 5.3, and 5.3.1


How can we reproduce this behavior?

The issue appears to be limited to the combination of ACF Content Analysis for Yoast SEO 2.0.0 and at the latest Yoast SEO Premium versions (5.2, 5.3, 5.3.1, and 5.3.2)

**Comment by martijnvaneeghem** [comment] 2017-08-25 10:09
Please inform the customer of conversation # 217264 when this conversation has been closed.

**Comment by martijnvaneeghem** [comment] 2017-08-25 10:10
Please inform the customer of conversation # 217560 when this conversation has been closed.

**Comment by Pcosta88** [comment] 2017-08-28 21:45
Please inform the customer of conversation # 218201 when this conversation has been closed.

**Comment by Pcosta88** [comment] 2017-09-15 20:12
Please inform the customer of conversation # 228164 when this conversation has been closed.

**Comment by Pcosta88** [comment] 2017-09-15 21:56
Please inform the customer of conversation # 228309 when this conversation has been closed.

**Comment by Pcosta88** [comment] 2017-09-19 21:27
Please inform the customer of conversation # 226035 when this conversation has been closed.

**Comment by Pcosta88** [comment] 2017-09-19 21:28
User reports

> We've had a look into the issue and it seems to be caused by the 'ACF
> Content Analysis for Yoast SEO' plugin. When the plugin is disabled, we're
> able to see the UI for the 'Content Optimisation' and 'Social' sections.
> When the plugin is enabled, the content is still there, but hidden. The
> following CSS selector is causing the issue:
> 
> ".wpseotab.facebook>.yoast-metabox__description, .wpseotab.facebook>input,
> .wpseotab.facebook>label, .wpseotab.facebook>textarea,
> .wpseotab.twitter>.yoast-metabox__description, .wpseotab.twitter>input,
> .wpseotab.twitter>label, .wpseotab.twitter>textarea {display: none; }"
> 
> As far as I can see no JS files are conflicting, but I can look into this
> further if it's likely a JS issue and not related to CSS.

**Comment by jack-pallot** [comment] 2017-09-21 08:47
I put the report directly above together for our marketing team to send. I'm happy to provide any additional details that could help with fixing the issue. Just let me know.

**Comment by kraftner** [comment] 2017-09-21 11:44
Hi @jack-pallot and thanks for the report. I suspect that this might be fixed by #67 but I didn't yet find the time to try. Maybe you have. :wink:

**Comment by Pcosta88** [comment] 2017-10-09 22:12
Please inform the customer of conversation # 240130 when this conversation has been closed.

**Comment by Pcosta88** [comment] 2017-10-10 19:56
Please inform the customer of conversation # 240694 when this conversation has been closed.

**Comment by Pcosta88** [comment] 2017-10-12 14:48
Please inform the customer of conversation # 240667 when this conversation has been closed.

**Comment by kraftner** [comment] 2017-10-12 14:50
I've just merged #67 into `develop` in case someone feels like trying if that fixed this issue.

**Comment by jack-pallot** [comment] 2017-10-12 16:43
I cloned the previous develop branch but I couldn't get it to run. Is there any other setup required with composer or NPM?

**Comment by kraftner** [comment] 2017-10-16 15:30
@jack-pallot No, this should be working out of the box. Weird. Any errors? Is the plugin visible in the backend?

**Comment by michaelbriantina** [comment] 2017-10-17 02:35
Please inform the customer of conversation # 244186 when this conversation has been closed.

**Comment by mariusghitulescu** [comment] 2017-10-17 16:56
Please inform the customer of conversation # 244585 when this conversation has been closed.

**Comment by mariusghitulescu** [comment] 2017-10-17 16:57
Please inform the customer of conversation # 244672 when this conversation has been closed.

**Comment by mariusghitulescu** [comment] 2017-10-17 20:16
Please inform the customer of conversation # 244679 when this conversation has been closed.

**Comment by moorscode** [comment] 2017-10-18 14:04
This will be resolved by https://github.com/Yoast/yoast-acf-analysis/pull/67 and will be released in 2.0.1

**Closed by moorscode** 2017-10-18 14:04 UTC
Labels: bug, support
