### ISSUE TITLE
Javascript errors when click on a ACF repeater

### ISSUE THREAD

**Issue by giofilo** [Yoast/yoast-acf-analysis#69] opened 2017-09-02 09:48 UTC
Hi,

When I active this plugin, I can't use ACF repeater.
When I click on the button to add a row in a repeater, it gives this javascript error:

`Uncaught TypeError: Cannot set property 'replacement' of undefined
    at replacevars.js:48
    at Function.m.each.m.forEach (load-scripts.php:93)
    at App.updateReplaceVars (replacevars.js:44)
    at d (acf-input.min.js:1)
    at Object.i (acf-input.min.js:1)
    at Object.do_action (acf-input.min.js:1)
    at acf-input.min.js:1`

I have to disable the plugin for now :(

Thank you!

**Comment by kraftner** [comment] 2017-09-08 11:03
Duplicate of #60

**Closed by kraftner** 2017-09-08 11:03 UTC
