### ISSUE TITLE
Uncaught TypeError: Cannot set property 'replacement' of undefined shows after trying to use layout rows

### ISSUE THREAD

**Issue by mhunt** [Yoast/yoast-acf-analysis#82] opened 2017-09-26 02:04 UTC
This issue is preventing the user from being able to delete a layout row once added. The error shows up in the console on the page/post edit screen once a new layout row is added. 

**See error:**
<img width="461" alt="screenshot 2017-09-25 21 57 59" src="https://user-images.githubusercontent.com/110907/30838954-a4615686-a23c-11e7-9da5-fa3d5b7c0d25.png">

I found almost the same issue with another acf related plugin: https://wordpress.org/support/topic/image-crop-add-on-broken/ 

It could have something to do with one of the latest releases. 

But the site which I found the error on, just had the acf analysis plugin installed as it's only acf related add-on plugin. When the plugin is deactivated, the error is gone and all works again.

**Versions:**

- ACF: 5.6.2 
- WP: 4.8.2
- Yoast ACF Analysis:  2.0.0 
- Chrome: 60

**Comment by kraftner** [comment] 2017-09-26 08:46
Thanks for reporting, I am closing this as a duplicate of #60 for which there is a #63 almost ready to be merged.

**Closed by kraftner** 2017-09-26 08:46 UTC
