### ISSUE TITLE
Yoast-ACF-Analysis Breaks Social Preview

### ISSUE THREAD

**Issue by intensitybands** [Yoast/yoast-acf-analysis#70] opened 2017-09-07 22:54 UTC
If you're not already aware of this, when the ACF Analysis plug-in is activated, you can no longer see any social previews in the Yoast plug-in.  

Please advise when fixed.  Thanks!

**Comment by kraftner** [comment] 2017-09-08 11:04
Duplicate of #21

**Closed by kraftner** 2017-09-08 11:04 UTC
